name: edgeca
base: core18
type: app
adopt-info: version
summary: An ephemeral, in-memory CA
description: |
  An ephemeral, in-memory CA providing service mesh machine identities

grade: stable
confinement: strict

apps:
  edgeca:
    adapter: none
    command: bin/edgeca
    plugs: [home, network]

  edgecad:
    adapter: none
    daemon: simple
    command: bin/edgecad-wrapper.sh
    plugs: [home, network, network-bind]

parts:
  version:
    plugin: nil
    source: .
    override-pull: |
      cd $SNAPCRAFT_PROJECT_DIR
      VERSION=$(git describe --tags --abbrev=0 | sed 's/^.//')
      snapcraftctl set-version ${VERSION}

  go-build-helper:
    plugin: dump 
    source: snap/local/
    build-snaps:
      - go/1.16/stable
    prime: [-*] 

  edgeca:
    source: . 
    plugin: make 
    after: [go-build-helper]
    build-packages: [git]

    override-build: |
      export PATH="$SNAPCRAFT_STAGE/go/bin:$GOPATH/bin:$PATH"
      cd $SNAPCRAFT_PART_SRC
      
      go build ./cmd/edgeca
      go build ./cmd/edgecad

      install -DT "./edgeca" "$SNAPCRAFT_PART_INSTALL/bin/edgeca"
      install -DT "./edgecad" "$SNAPCRAFT_PART_INSTALL/bin/edgecad"
      
  config-common:
      plugin: dump
      source: snap/local/runtime-helpers
