name: edgeca
base: core18
type: app
adopt-info: version
summary: An ephemeral, in-memory CA
description: |
  An ephemeral, in-memory CA providing service mesh machine identities. 

grade: stable
confinement: strict

apps:
  edgeca:
    adapter: none
    command: bin/edgeca 
    plugs: [home, network, network-bind]
 

parts:
  version:
    plugin: nil
    source: snap/local/
    override-pull: |
      cd $SNAPCRAFT_PROJECT_DIR
      VERSION=$(git describe --tags --abbrev=0 | sed 's/^.//')
      snapcraftctl set-version ${VERSION}

  go-build-helper:
    plugin: dump 
    source: snap/local/
    build-snaps:
      - go/1.16/stable
    prime: [-*] 

  edgeca:
    source: . 
    plugin: make 
    after: [go-build-helper]
    build-packages: [git]
    override-build: |
      export PATH="$SNAPCRAFT_STAGE/go/bin:$GOPATH/bin:$PATH"
      cd $SNAPCRAFT_PART_SRC
      make
      install -DT "./bin/edgeca" "$SNAPCRAFT_PART_INSTALL/bin/edgeca" 

  softhsm:
    source: .
    plugin: make 
    build-packages:
      - autoconf
      - automake
      - libtool
      - libssl-dev
      - wget
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      SOFTHSMV2_VERSION=2.6.1
      wget -O SoftHSMv2.tar.gz https://github.com/opendnssec/SoftHSMv2/archive/${SOFTHSMV2_VERSION}.tar.gz
      tar -xf SoftHSMv2.tar.gz
      cd SoftHSMv2-${SOFTHSMV2_VERSION}
      ./autogen.sh
      ./configure
      make
      install -D $SNAPCRAFT_PART_SRC/SoftHSMv2-${SOFTHSMV2_VERSION}/src/lib/.libs/libsofthsm2.so $SNAPCRAFT_PART_INSTALL/usr/lib/softhsm/libsofthsm2.so  
      # ranlib /usr/local/lib/softhsm/libsofthsm2.a

